# Generated by Django 3.2.5 on 2023-12-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='is_creator',
        ),
    ]
