# Generated by Django 3.2.5 on 2023-12-05 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0009_auto_20231205_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_projects', through='support.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
